# Generated by Django 3.1.2 on 2020-10-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('', 'Not Selected'), ('admin', 'Admin'), ('finance', 'Finance'), ('program', 'Program'), ('m&e', 'M&E'), ('communications', 'Communications'), ('it', 'IT')], default='', max_length=20)),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('adminstrator', 'Adminstrator')], default='staff', max_length=12)),
            ],
        ),
    ]
