# Generated by Django 3.1.2 on 2020-10-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
