# Generated by Django 3.1.2 on 2020-10-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201018_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('adminstrator', 'Adminstrator')], default=('staff', 'Staff'), max_length=12),
        ),
    ]
