# Generated by Django 3.1.2 on 2020-10-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201019_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_2',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
