# Generated by Django 3.1.2 on 2020-10-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201020_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_2',
        ),
    ]
