# Generated by Django 3.1.2 on 2020-10-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201020_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Finance', 'Finance'), ('Program', 'Program'), ('M&E', 'M&E'), ('Communications', 'Communications'), ('IT', 'IT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('administrator', 'Administrator')], default=('staff', 'Staff'), max_length=13),
        ),
    ]
