# Generated by Django 3.1.2 on 2020-10-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clockin',
            name='slug',
            field=models.SlugField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='clockin',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
