# Generated by Django 3.1.2 on 2020-10-18 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0002_auto_20201017_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 10, 18, 14, 37, 33, 971446), null=True),
        ),
    ]
