# Generated by Django 3.1.2 on 2020-10-18 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0003_auto_20201018_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 10, 18, 15, 8, 22, 888742), null=True),
        ),
    ]
