# Generated by Django 3.1.2 on 2020-10-18 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0004_auto_20201018_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 10, 18, 15, 38, 27, 802600), null=True),
        ),
    ]
