# Generated by Django 3.1.2 on 2020-10-19 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0006_auto_20201018_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 10, 19, 19, 17, 14, 111502), null=True),
        ),
    ]
