# Generated by Django 3.1.2 on 2020-10-19 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0007_auto_20201019_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 10, 19, 19, 29, 0, 480222), null=True),
        ),
    ]
