# Generated by Django 3.1.2 on 2020-10-20 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0008_auto_20201019_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 10, 20, 12, 14, 48, 393236), null=True),
        ),
    ]
