# Generated by Django 3.1.2 on 2020-10-20 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0009_auto_20201020_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 10, 20, 18, 47, 47, 238906), null=True),
        ),
    ]
