# Generated by Django 3.1.2 on 2020-10-22 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0010_auto_20201020_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 10, 23, 0, 43, 49, 906319), null=True),
        ),
    ]
