# Generated by Django 3.1.2 on 2020-10-29 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0011_auto_20201023_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 10, 29, 19, 46, 43, 406621), null=True),
        ),
    ]
