# Generated by Django 3.1.2 on 2020-11-07 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0012_auto_20201029_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 11, 7, 21, 51, 22, 759684), null=True),
        ),
    ]
