# Generated by Django 3.1.2 on 2020-11-10 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0014_auto_20201109_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 11, 10, 21, 46, 30, 537221), null=True),
        ),
    ]
