# Generated by Django 3.1.2 on 2020-11-12 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0015_auto_20201110_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='time_status',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 11, 12, 10, 49, 4, 476987), null=True),
        ),
    ]
