# Generated by Django 3.1.2 on 2020-11-12 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0016_auto_20201112_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 11, 12, 11, 5, 19, 515150), null=True),
        ),
        migrations.AlterField(
            model_name='clockin',
            name='time_status',
            field=models.CharField(choices=[('early', 'Early'), ('late', 'Late')], max_length=5, null=True),
        ),
    ]
