# Generated by Django 3.1.2 on 2020-11-12 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
        ('clockin', '0017_auto_20201112_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clockins', to='day.day'),
        ),
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 11, 12, 12, 35, 42, 192461), null=True),
        ),
    ]
