# Generated by Django 3.1.2 on 2020-11-14 16:18

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0018_auto_20201112_1235'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clockin',
            managers=[
                ('punctual', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 11, 14, 17, 18, 24, 53644), null=True),
        ),
    ]
