# Generated by Django 3.1.2 on 2020-11-14 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0019_auto_20201114_1718'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clockin',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 11, 14, 19, 11, 20, 17823), null=True),
        ),
    ]
