# Generated by Django 3.1.2 on 2020-11-17 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0020_auto_20201114_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 11, 17, 4, 53, 25, 210408), null=True),
        ),
    ]
