# Generated by Django 3.1.2 on 2020-12-14 15:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('day', '0001_initial'),
        ('clockin', '0021_auto_20201117_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 12, 14, 16, 30, 24, 525615), null=True),
        ),
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='14 December, 2020', max_length=50)),
                ('reason', models.TextField(blank=True, default='None')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absents', to='day.day')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
